Section "InputClass"
  Identifier "XP-Pen Artist 12 Pro Pen"
  MatchIsTablet "on"
  MatchProduct "Pen"
  Driver "wacom"
  MatchUSBID "28bd:091f"
  MatchDevicePath "/dev/input/event*"
EndSection

Section "InputClass"
  Identifier "XP-Pen Artist 12 Pro Pad"
  MatchIsKeyboard "on"
  MatchProduct "Pad"
  Driver "wacom"
  MatchUSBID "28bd:091f"
  MatchDevicePath "/dev/input/event*"
EndSection
