# Send prefix
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

# Use Alt-arrow keys to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window

# Mouse mode
setw -g mouse on

# Set easier window split keys
bind-key h split-window -h
bind-key v split-window -v

# Removes esc lag in vim
set -sg escape-time 0

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# Cutomization
set-option -g status-position bottom    # bar position
set-option -g status-style bg=black,fg=white    # bar color

set-option -g status-left '#[bold]#(echo "T-Ses:")#{session_name}'
set-option -g status-left-length 10

set-option -g status-justify centre

set-option -g status-right ''

set-option -g automatic-rename on   # change name of the window to program

set-option -g window-status-format '#{window_index}#(echo ":")#{window_name}'
set-option -g window-status-current-format '#[bold,fg=black,bg=white]#{window_index}#(echo ":")#{window_name}'

