#!/bin/sh

destination_dir="$HOME/Documents/apps"
bin_folder="$HOME/.local/bin"
app_name="blender"

version_folder=$(ls $destination_dir/$app_name)
executable="$destination_dir/$app_name/$version_folder/$app_name"

$executable
